# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod "AFNetworking", "~> 2.0"
pod 'SVProgressHUD', "~> 1.1.3"
pod 'Gryphon', '~> 3.1'
pod "Siesta", "~> 1.0"
pod 'Alamofire', '~> 4.7'
pod 'Siesta/Alamofire', '~> 1.0'

target 'MinecraftServerList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MinecraftServerList

  target 'MinecraftServerListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
